### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by L33t33L** [ElSicarius/chunkloader#2]
Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

![Screenshot_2024-07-20_09-42-48](https://github.com/user-attachments/assets/4182c2e5-fe49-47a4-9431-069915ed523d)

**Comment by ElSicarius** [comment]
You should definitely read the readme before creating issues on GitHub projects mate...

That being said, I'm still open to contribs !

Cheers.
